name: CI

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0

      - name: Install Webpack
        run: npm install --save-dev webpack-cli --legacy-peer-deps

      #- name: Update Deps
      #  run: npm run build:deps

      - name: Update locales
        run: npm run update:locale

      - name: Update Addon Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: ./update.sh ${{matrix.os}}

      - name: Update Addon
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          ./update.sh ${{matrix.os}} arm
          ./update.sh ${{matrix.os}} amd

      - name: Build Mac Version
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          ELECTRON_SKIP_NOTARIZE=1 ELECTRON_SKIP_SENTRY=1 npm run dist:mac

      - name: Build Windows Version
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          ELECTRON_SKIP_NOTARIZE=1 ELECTRON_SKIP_SENTRY=1 npm run dist:win

      - name: Build Linux Version
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          ELECTRON_SKIP_SENTRY=1 npm run dist:linux
